x-environment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_2025_postgis'
    container_name: prge-2025-postgis${ENV_NAME}
    environment:
      - *env-postgres-user
      - *env-postgres-password
      - *env-postgres-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-local-data:/var/lib/postgresql/data


volumes:
  postgis-local-data: