name: build_and_push_and_deploy
on:
  push:
    branches:
      - env-test

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      -self-hosted
    environment: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'witaj'

      - name: uruchom-Å›rodowisko-docker-compose
        env:
          ENV_NAME: ${{github.ref_name}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          #DB
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-local.yml -p remote-prge up --build -d

