name: build and push and deploy

on:
  push:
    branches:
      - env-test
      - env-qa
      - main


permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    name: Build & Push
    runs-on:
      - self-hosted
    environment: ${{github.ref_name}}

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'witam'


      - name: uruchom srodowisko docker-compose
        env:
          ENV_NAME: ${{github.ref_name}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          GEOSERVER_PORT: ${{secrets.GEOSERVER_PORT}}
          #DB
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-remote.yml -p remote-prge up --build -d